name: os-ovr-loss-weighted

channels:
  - default
  - pytorch
  - nvidia

dependencies:
  - python=3.10
  - pandas>=1.4.3
  - numpy>=1.22.3
  - matplotlib>=3.5.2
  - pytorch-cuda>=1.11.0
  - torchvision>=0.12.0
  - tqdm>=4.64.0
  - scikit-learn>=1.4.2
  - wget
  - pyyaml
  - pip
  - tensorboard