##########################################
# Evaluation Setup
##########################################
scale: smallscale   # smallscale / largescale_1 / largescale_2 / largescale_3
name: LeNet_neg_0         # LeNet or LeNet(+suffix) / ResNet_50 or ResNet_50(+suffix)
approach: OvR       # SoftMax / EOS / OvR

##########################################
# Dataset Setup
##########################################
data:
  smallscale:
    root: /local/scratch/hkim # EMNIST path
    label_filter: [-1] # # [-1] for using all labels. e.g. [0,1] only using 0 and 1 class data
  largescale:
    root: /local/scratch/datasets/ImageNet/ILSVRC2012 # ILSVRC2012 path
    protocol: /home/user/hkim/UZH-MT/os-ovr-loss-weighted/data/LargeScale # ImageNet Protocol root path

##########################################
# Architecture Setup
##########################################
arch:
  model_root: ./models
  feat_dim: -1  # -1 for using default value.

##########################################
# Evaluation Detail Setup
##########################################
batch_size: 
  smallscale: 2048 # Fixed
  largescale: 256 # Fixed
pred_save: 1    # Set as '1' if you want to save the prediction results
openset_save: 1    # Set as '1' if you want to save the openset performance data
